sonar.projectKey=SergioBejarano_Shipwreckeds-Front
sonar.organization=sergiobejarano
sonar.projectName=Shipwreckeds-Front
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
